package(default_visibility = ["//visibility:public"])

licenses(["notice"])

proto_library(
    name = "descriptor_proto",
    srcs = ["descriptor.proto"],
)

proto_library(
    name = "field_mask_proto",
    srcs = ["field_mask.proto"],
)

proto_library(
    name = "timestamp_proto",
    srcs = ["timestamp.proto"],
)

proto_library(
    name = "wrappers_proto",
    srcs = ["wrappers.proto"],
)

