package(default_visibility = ["//visibility:public"])

licenses(["notice"])

proto_library(
    name = "status_proto",
    srcs = ["status.proto"],
    deps = ["//google/protobuf:any_proto"],
)

proto_library(
    name = "error_details_proto",
    srcs = ["error_details.proto"],
    deps = ["//google/protobuf:duration_proto"],
)

proto_library(
    name = "code_proto",
    srcs = ["code.proto"],
)

