package(default_visibility = ["//visibility:public"])

licenses(["notice"])

proto_library(
    name = "bytestream_proto",
    srcs = ["bytestream.proto"],
    deps = [
        "//google/api:annotations_proto",
        "//google/protobuf:wrappers_proto",
    ],
)
